-- 002_members_seed.sql (auto-generated by scripts/seed-from-data.ts)
-- src/data/members.ts → INSERT 변환

INSERT INTO members (name_en, name_kr, position, photo_url, favorite_artist, favorite_song, display_order, published) VALUES
('Yeongmin Kim', '김영민', 'Song writer / Vocal / Guitar', '/members/member01.jpg', 'Oasis / John Mayer', 'Don''t look back in anger / Waiting on the world to change', 1, 1),
('Minjae Kim', '김민재', 'Song writer / Vocal / Guitar', '/members/member02.jpg', 'Oasis', 'Slide away', 2, 1),
('Mihee Cho', '조미희', 'Bass', '/members/member03.jpg', '우원재', '호불호', 3, 1),
('Seongsu Hong', '홍성수', 'Drums', '/members/member04.jpg', 'John Mayer', 'Slow dancing in a burning room', 4, 1),
('Hyungseung Lee', '이형승', 'Keyboard', '/members/member05.jpg', 'Oasis / Blur', 'Live forever / Coffee and TV', 5, 1),
('Yevin Kim', '김예빈', 'Drums', '/members/member06.jpg', '緑黄色社会*녹황색사회 / 쏜애플', '完全感覚Dreamer / 秒針を噛む', 6, 1),
('Sangjun Kim', '김상준', 'Drums / Support', '/members/member07.jpg', 'Radiohead / The Beatles', 'Let down / Penny lane', 7, 1),
('Sihyun Ham', '함시현', 'Manager / Designer / Support', '/members/member08.jpg', 'Oasis / Coldplay', 'Champagne supernova / Fix you', 8, 1),
('Raehyuk Jung', '정래혁', 'Designer / Support', '/members/member09.jpg', 'The Beatles / 잔나비', 'Tomorrow Never Knows / 꿈과 책과 힘과 벽', 9, 1);
