import { writeFileSync } from "node:fs";
import { members } from "../src/data/members";
import { songs } from "../src/data/songs";
import { news } from "../src/data/news";

function esc(s: string | null | undefined): string {
  if (s == null) return "NULL";
  return "'" + s.replace(/\\/g, "\\\\").replace(/'/g, "''") + "'";
}

// members
{
  const lines: string[] = [
    "-- 002_members_seed.sql (auto-generated by scripts/seed-from-data.ts)",
    "-- src/data/members.ts → INSERT 변환",
    "",
    "INSERT INTO members (name_en, name_kr, position, photo_url, favorite_artist, favorite_song, display_order, published) VALUES",
  ];
  const rows = members.map((m, i) => {
    const order = m.order ?? (i + 1);
    return `(${esc(m.nameEn)}, ${esc(m.nameKr)}, ${esc(m.position)}, ${esc(m.photo)}, ${esc(m.favoriteArtist)}, ${esc(m.favoriteSong)}, ${order}, 1)`;
  });
  lines.push(rows.join(",\n") + ";");
  writeFileSync("db/seed/002_members_seed.sql", lines.join("\n") + "\n");
  console.log(`Wrote ${rows.length} members`);
}

// songs
{
  const lines: string[] = [
    "-- 003_songs_seed.sql (auto-generated)",
    "",
    "INSERT INTO songs (title, category, artwork_url, listen_url, lyrics, released_at, published) VALUES",
  ];
  const rows = songs.map((s) => {
    return `(${esc(s.title)}, ${esc(s.category)}, ${esc(s.artwork)}, ${esc(s.listenUrl || null)}, ${esc(s.lyrics || null)}, ${esc(s.releasedAt)}, 1)`;
  });
  lines.push(rows.join(",\n") + ";");
  writeFileSync("db/seed/003_songs_seed.sql", lines.join("\n") + "\n");
  console.log(`Wrote ${rows.length} songs`);
}

// news
{
  const lines: string[] = [
    "-- 004_news_seed.sql (auto-generated)",
    "",
    "INSERT INTO news (headline, category, date, hero_image, body, mid_image, published) VALUES",
  ];
  const rows = news.map((n) => {
    return `(${esc(n.headline)}, ${esc(n.category)}, ${esc(n.date)}, ${esc(n.heroImage)}, ${esc(n.body)}, ${esc(n.midImage ?? null)}, 1)`;
  });
  lines.push(rows.join(",\n") + ";");
  writeFileSync("db/seed/004_news_seed.sql", lines.join("\n") + "\n");
  console.log(`Wrote ${rows.length} news`);
}

console.log("Done. Inspect db/seed/*.sql before applying.");
